// INTENT: Suggestions reduce blank-page work. Selecting or editing one writes
// the same Soul Markdown; these are not a second set of character attributes.
export const CREATE_SOUL_DETAIL_FIELDS = [
  {
    label: "Personality",
    suggestions: [
      "Warm and curious", "Playful and confident", "Shy and thoughtful",
      "Calm and protective", "Bold and adventurous", "Witty and observant",
      "Gentle and patient", "Direct and practical", "Quiet and perceptive",
      "Cheerful and encouraging", "Reserved and loyal", "Dreamy and imaginative",
      "Analytical and inquisitive", "Spontaneous and energetic", "Elegant and composed",
      "Mischievous and affectionate", "Sincere and idealistic", "Independent and determined",
      "Skeptical with a dry sense of humor", "Tender beneath a guarded exterior",
      "Competitive and gracious", "Carefree and easygoing", "Disciplined and ambitious",
      "Nurturing and grounded", "Eccentric and inventive", "Charismatic and theatrical",
      "Stoic and dependable", "Passionate and expressive", "Bookish and introspective",
      "Diplomatic and empathetic", "Rebellious and outspoken", "Meticulous and methodical",
      "Optimistic and resilient", "Melancholic and poetic", "Adventurous but cautious",
      "Sociable and hospitable", "Soft-spoken and steadfast", "Assertive and considerate",
      "Whimsical and lighthearted", "Intense and focused", "Humble and resourceful",
      "Clever and teasing", "Philosophical and reflective", "Romantic and sentimental",
      "Candid and irreverent", "Secretive and enigmatic", "Pragmatic and compassionate",
      "Fearless and principled",
    ],
  },
  {
    label: "Occupation",
    suggestions: [
      "Artist", "Teacher", "Writer", "Musician", "Chef", "Doctor", "Scientist",
      "Entrepreneur", "Adventurer", "Architect", "Interior designer", "Graphic designer",
      "Fashion designer", "Illustrator", "Animator", "Photographer", "Filmmaker",
      "Actor", "Theater director", "Screenwriter", "Poet", "Journalist", "Editor",
      "Translator", "Librarian", "Archivist", "Curator", "Art restorer", "Sculptor",
      "Potter", "Jeweler", "Tattoo artist", "Florist", "Baker", "Pastry chef",
      "Barista", "Bartender", "Sommelier", "Restaurant owner", "Hotel manager",
      "Tour guide", "Flight attendant", "Pilot", "Ship captain", "Marine biologist",
      "Oceanographer", "Astronomer", "Astronaut", "Physicist", "Chemist", "Biologist",
      "Botanist", "Geologist", "Archaeologist", "Anthropologist", "Historian",
      "Mathematician", "Data scientist", "Software engineer", "Game developer",
      "Robotics engineer", "Mechanical engineer", "Civil engineer", "Electrical engineer",
      "Environmental engineer", "Urban planner", "Landscape architect", "Carpenter",
      "Blacksmith", "Watchmaker", "Tailor", "Mechanic", "Electrician", "Plumber",
      "Farmer", "Beekeeper", "Winemaker", "Gardener", "Park ranger", "Wildlife rescuer",
      "Veterinarian", "Animal trainer", "Nurse", "Paramedic", "Surgeon", "Dentist",
      "Pharmacist", "Physiotherapist", "Psychologist", "Nutritionist", "Yoga instructor",
      "Personal trainer", "Dance instructor", "Professional dancer", "Athlete",
      "Martial arts instructor", "Climbing instructor", "Surf instructor", "Ski instructor",
      "Firefighter", "Rescue diver", "Detective", "Lawyer", "Mediator", "Diplomat",
      "Social worker", "Community organizer", "Museum educator", "University lecturer",
      "Language tutor", "Music teacher", "Composer", "Sound engineer", "Radio host",
      "Podcaster", "Event planner", "Wedding planner", "Stage manager", "Luthier",
      "Bookshop owner", "Antique dealer", "Board game designer", "Escape room designer",
      "Travel writer", "Documentary researcher", "Conservationist", "Sailing instructor",
      "Mountain guide", "Courier", "Train conductor", "Private investigator",
      "Fantasy cartographer", "Alchemist", "Spaceship engineer", "Guild leader",
    ],
  },
  {
    label: "Relationship",
    suggestions: [
      "New acquaintance", "Friend", "Childhood friend", "Best friend", "Romantic partner",
      "Spouse", "Roommate", "Rival", "Neighbor", "Colleague", "Business partner",
      "Creative collaborator", "Travel companion", "Pen pal", "Long-distance partner",
      "Former partner reconnecting", "Friend becoming a partner", "Secret admirer",
      "Blind date", "Book club friend", "Bandmate", "Teammate", "Fellow adventurer",
      "Mentor", "Mentee", "Friendly competitor", "Old friend reunited",
      "Stranger met by chance", "Allies with a shared mission",
    ],
  },
  { label: "Hobbies", suggestions: ["Reading", "Music", "Cooking", "Gaming", "Hiking", "Photography", "Stargazing"] },
  { label: "Fetishes and preferences", suggestions: ["Romance", "Playful flirting", "Praise", "Roleplay"] },
] as const;
