import { z } from "zod";
import {
  adminCursorQuerySchema,
  adminIsoDateTimeSchema,
  adminListResponseSchema,
} from "./common";

export const metricAsOfQuerySchema = z.object({
  asOf: adminIsoDateTimeSchema.optional(),
}).strict();
export const metricDashboardQuerySchema = metricAsOfQuerySchema;
export const metricQualityQuerySchema = metricAsOfQuerySchema;
export const metricReconciliationQuerySchema = metricAsOfQuerySchema;

export const metricQualityStateSchema = z.enum(["certified", "directional", "invalid", "stale"]);
export const metricDecisionUseSchema = z.enum(["allowed", "directional_only", "blocked"]);
export const metricPublicationStatusSchema = z.enum(["official", "shadow", "diagnostic", "guardrail"]);

export const metricDefinitionSchema = z
  .object({
    key: z.string().trim().min(1),
    name: z.string().trim().min(1),
    description: z.string().trim().min(1),
    businessQuestion: z.string().trim().min(1),
    numerator: z.string().trim().min(1),
    denominator: z.string().trim().min(1),
    grain: z.string().trim().min(1),
    sourceFacts: z.array(z.string().trim().min(1)).min(1).readonly(),
    sourceEvents: z.array(z.string().trim().min(1)).min(1).readonly(),
    requiredTrustClasses: z.array(z.string().trim().min(1)).min(1).readonly(),
    exclusions: z.array(z.string().trim().min(1)).readonly(),
    cohort: z.string().trim().min(1),
    window: z.string().trim().min(1),
    timezone: z.string().trim().min(1),
    maturity: z.string().trim().min(1),
    dedupe: z.string().trim().min(1),
    attributionRule: z.string().trim().min(1),
    owner: z.string().trim().min(1),
    publicationStatus: metricPublicationStatusSchema,
    decisionGate: z.string().trim().min(1).nullable(),
    version: z.number().int().positive(),
    effectiveAt: adminIsoDateTimeSchema,
    validFrom: adminIsoDateTimeSchema,
    queryHash: z.string().trim().min(1),
    freshnessSlo: z
      .object({
        maxAgeSeconds: z.number().int().positive(),
      })
      .strict(),
    qualityState: metricQualityStateSchema,
    decisionUse: metricDecisionUseSchema,
    lastValidatedAt: adminIsoDateTimeSchema.nullable(),
    validationEvidence: z.array(z.string().trim().min(1)).readonly(),
  })
  .strict()
  .superRefine((definition, ctx) => {
    const expectedDecisionUse =
      definition.qualityState === "certified"
        ? "allowed"
        : definition.qualityState === "directional"
          ? "directional_only"
          : "blocked";
    if (definition.decisionUse !== expectedDecisionUse) {
      ctx.addIssue({
        code: "custom",
        path: ["decisionUse"],
        message: `Quality state ${definition.qualityState} requires ${expectedDecisionUse}`,
      });
    }
  });

export const metricCardSchema = z
  .object({
    key: z.string().trim().min(1),
    definitionVersion: z.number().int().positive(),
    publicationStatus: metricPublicationStatusSchema,
    name: z.string().trim().min(1),
    value: z.union([z.number(), z.string(), z.null()]),
    unit: z.string().trim().min(1),
    numeratorLabel: z.string().trim().min(1),
    denominatorLabel: z.string().trim().min(1),
    numeratorValue: z.number().nullable(),
    denominatorValue: z.number().nullable(),
    sampleSize: z.number().int().nonnegative(),
    matureSampleSize: z.number().int().nonnegative(),
    immatureSampleSize: z.number().int().nonnegative(),
    window: z.string().trim().min(1),
    timezone: z.literal("UTC"),
    maturity: z.enum(["mature", "immature", "insufficient_data"]),
    asOf: adminIsoDateTimeSchema,
    validFrom: adminIsoDateTimeSchema,
    latestDataAt: adminIsoDateTimeSchema.nullable(),
    qualityState: metricQualityStateSchema,
    decisionUse: metricDecisionUseSchema,
    qualityEvidence: z.array(z.string().trim().min(1)).readonly(),
  })
  .strict()
  .superRefine((card, ctx) => {
    if (card.numeratorValue !== null && card.denominatorValue !== null && card.numeratorValue > card.denominatorValue) {
      ctx.addIssue({ code: "custom", path: ["numeratorValue"], message: "Numerator must belong to denominator cohort" });
    }
    if ((card.qualityState === "invalid" || card.qualityState === "stale") && card.value !== null) {
      ctx.addIssue({ code: "custom", path: ["value"], message: "Invalid or stale metrics must fail closed with value=null" });
    }
  });

export const metricQualityReportSchema = z.object({
  asOf: adminIsoDateTimeSchema,
  qualityState: z.enum(["certified", "invalid"]),
  incompleteOutcomeCount: z.number().int().nonnegative(),
  duplicateEffectCount: z.number().int().nonnegative(),
  impossibleStateCount: z.number().int().nonnegative(),
  fixtureInternalLeakageCount: z.number().int().nonnegative(),
  joinCoverage: z.number().min(0).max(1),
  userJoinCoverage: z.number().min(0).max(1),
  characterJoinCoverage: z.number().min(0).max(1),
  contentVersionJoinCoverage: z.number().min(0).max(1),
  releaseJoinCoverage: z.number().min(0).max(1),
  eventLagP95Ms: z.number().int().nonnegative().nullable(),
  freshnessSloMs: z.number().int().positive(),
  scannedFactCount: z.number().int().nonnegative(),
  checks: z.array(z.object({
    key: z.string().min(1),
    status: z.enum(["passed", "failed", "unavailable"]),
    observed: z.union([z.number(), z.string(), z.null()]),
    threshold: z.string().min(1),
  }).strict()).readonly(),
}).strict();

export const metricDashboardResponseSchema = z.object({
  definitions: z.array(metricDefinitionSchema).readonly(),
  cards: z.array(metricCardSchema).readonly(),
  quality: metricQualityReportSchema,
  asOf: adminIsoDateTimeSchema,
  freshness: z.enum(["fresh", "stale", "degraded"]),
}).strict();

export const metricReconciliationReportSchema = z.object({
  asOf: adminIsoDateTimeSchema,
  quality: metricQualityReportSchema,
  recentBackfills: z.array(z.object({
    runId: z.string().min(1),
    source: z.string().min(1),
    status: z.string().min(1),
    dryRun: z.boolean(),
    cursor: z.string().nullable(),
    scannedCount: z.number().int().nonnegative(),
    appliedCount: z.number().int().nonnegative(),
    skippedCount: z.number().int().nonnegative(),
    mismatchCount: z.number().int().nonnegative(),
    coverage: z.number().min(0).max(1).nullable(),
    validFrom: adminIsoDateTimeSchema.nullable(),
    startedAt: adminIsoDateTimeSchema,
    completedAt: adminIsoDateTimeSchema.nullable(),
  }).strict()).readonly(),
}).strict();

export const metricQuerySchema = adminCursorQuerySchema.extend({
  qualityState: metricQualityStateSchema.optional(),
  owner: z.string().trim().min(1).optional(),
});

export const metricListResponseSchema = adminListResponseSchema(metricCardSchema);

export type MetricDefinition = z.infer<typeof metricDefinitionSchema>;
export type MetricCard = z.infer<typeof metricCardSchema>;
export type MetricQuery = z.infer<typeof metricQuerySchema>;
export type MetricQualityReport = z.infer<typeof metricQualityReportSchema>;
export type MetricDashboardResponse = z.infer<typeof metricDashboardResponseSchema>;
export type MetricReconciliationReport = z.infer<typeof metricReconciliationReportSchema>;

export function defineMetricRegistry(definitions: readonly MetricDefinition[]): readonly MetricDefinition[] {
  const parsed = definitions.map((definition) => metricDefinitionSchema.parse(definition));
  const seen = new Set<string>();
  for (const definition of parsed) {
    const identity = `${definition.key}@${definition.version}`;
    if (seen.has(identity)) throw new Error(`Duplicate metric definition: ${identity}`);
    seen.add(identity);
  }
  return Object.freeze(parsed);
}

const invalidLegacyDefaults = {
  grain: "eligible_customer",
  sourceFacts: ["legacy_admin_analytics"] as const,
  sourceEvents: ["legacy.unversioned.event"] as const,
  requiredTrustClasses: ["canonical"] as const,
  exclusions: ["internal actors", "fixture data", "non-production data"] as const,
  cohort: "legacy cohort pending canonical v2 backfill",
  timezone: "UTC",
  maturity: "not certified",
  dedupe: "legacy dedupe is not decision-grade",
  attributionRule: "none",
  owner: "Growth Analytics",
  publicationStatus: "diagnostic" as const,
  decisionGate: null,
  version: 1,
  effectiveAt: "2026-07-11T00:00:00.000Z",
  validFrom: "2026-07-11T00:00:00.000Z",
  freshnessSlo: { maxAgeSeconds: 86400 },
  qualityState: "invalid" as const,
  decisionUse: "blocked" as const,
  lastValidatedAt: null,
  validationEvidence: [] as const,
};

const canonicalMetricDefaults = {
  grain: "eligible_user",
  sourceFacts: ["customer_signup_fact", "chat_exchange_fact", "generation_fulfillment_fact", "subscription_lifecycle_fact"] as const,
  sourceEvents: ["customer.signup.completed.v2", "chat.exchange.completed.v2", "chat.exchange.corrected.v2", "generation.delivery.completed.v2", "subscription.activated.v2", "subscription.ended.v2"] as const,
  requiredTrustClasses: ["canonical"] as const,
  exclusions: ["internal actors", "fixture data", "non-production data", "non-customer data", "duplicate source events"] as const,
  cohort: "eligible customer facts using occurredAt",
  timezone: "UTC",
  maturity: "metric-specific closed observation window",
  dedupe: "canonical source key; exchangeId for logical chat turns; requestId for generation delivery",
  attributionRule: "none unless exact release/placement context is present",
  owner: "Growth Analytics",
  publicationStatus: "diagnostic" as const,
  decisionGate: null,
  version: 1,
  effectiveAt: "2026-07-11T00:00:00.000Z",
  validFrom: "2026-07-11T00:00:00.000Z",
  freshnessSlo: { maxAgeSeconds: 3600 },
  // A checked-in definition is only a formula candidate. Decision authority is
  // granted later by a published MetricDefinitionSnapshot plus fresh persisted
  // quality/materialization evidence; source code must never self-certify.
  qualityState: "invalid" as const,
  decisionUse: "blocked" as const,
  lastValidatedAt: null,
  validationEvidence: [] as const,
};

export const ADMIN_METRIC_REGISTRY = defineMetricRegistry([
  {
    ...invalidLegacyDefaults,
    key: "legacy.activated_users",
    name: "Activated users (legacy)",
    description: "Legacy activated-user count retained for comparison only.",
    businessQuestion: "How does the legacy activation proxy compare with canonical activation?",
    numerator: "users matching the legacy activation proxy",
    denominator: "eligible signup cohort",
    window: "legacy implementation window",
    queryHash: "pending:legacy-activated-v1",
  },
  {
    ...invalidLegacyDefaults,
    key: "legacy.signup_to_paid_conversion",
    name: "Signup-to-paid conversion (legacy)",
    description: "Legacy conversion ratio without a certified cohort contract.",
    businessQuestion: "What did the legacy console label as conversion?",
    numerator: "legacy paying users",
    denominator: "legacy signups",
    window: "legacy implementation window",
    queryHash: "pending:legacy-conversion-v1",
  },
  {
    ...invalidLegacyDefaults,
    key: "legacy.same_character_d1",
    name: "Same-character D1 (legacy)",
    description: "Legacy D1 value pending QCE v1 and exact-day certification.",
    businessQuestion: "Do qualified pairs return to the same character on exact D0+1?",
    numerator: "legacy returning pairs",
    denominator: "legacy first-activity pair cohort",
    window: "exact D0+1 target; legacy implementation unverified",
    queryHash: "pending:legacy-d1-v1",
  },
  {
    ...invalidLegacyDefaults,
    key: "legacy.same_character_d7",
    name: "Same-character D7 (legacy)",
    description: "Legacy D7 value pending QCE v1 and exact-day certification.",
    businessQuestion: "Do qualified pairs return to the same character on exact D0+7?",
    numerator: "legacy returning pairs",
    denominator: "legacy first-activity pair cohort",
    window: "exact D0+7 target; legacy implementation unverified",
    queryHash: "pending:legacy-d7-v1",
  },
  {
    key: "flag_monitoring.exposure",
    name: "Flag Monitoring",
    description: "Directional monitoring for feature flags without randomized assignment and exposure facts.",
    businessQuestion: "Are operational outcomes changing while a feature flag is active?",
    numerator: "observed outcome events associated with the active flag window",
    denominator: "eligible observations in the flag window",
    grain: "flag_window",
    sourceFacts: ["feature_flag_state", "canonical_product_event"],
    sourceEvents: ["feature.flag.changed.v1", "product.event.v2"],
    requiredTrustClasses: ["canonical"],
    exclusions: ["internal actors", "fixture data", "non-production data"],
    cohort: "eligible observations while flag state is active",
    window: "operator-selected flag monitoring window",
    timezone: "UTC",
    maturity: "after the selected observation window closes",
    dedupe: "canonical source key",
    attributionRule: "correlation only; no causal claim",
    owner: "Growth Analytics",
    publicationStatus: "diagnostic",
    decisionGate: null,
    version: 1,
    effectiveAt: "2026-07-11T00:00:00.000Z",
    validFrom: "2026-07-11T00:00:00.000Z",
    queryHash: "pending:flag-monitoring-v1",
    freshnessSlo: { maxAgeSeconds: 3600 },
    qualityState: "directional",
    decisionUse: "directional_only",
    lastValidatedAt: null,
    validationEvidence: [],
  },
  {
    ...canonicalMetricDefaults,
    key: "north_star.wpcu",
    name: "Weekly Paying Companion Users",
    description: "Current PRD North Star: paid users with at least one eligible message exchange or successful generation delivery in the current UTC calendar week.",
    businessQuestion: "How many paying users reached either core value path this week?",
    numerator: "distinct eligible users with an active subscription overlapping the UTC calendar week and at least one eligible exchange or successful generation delivery during that week",
    denominator: "not applicable (count metric)",
    cohort: "eligible customer users with a subscription active at any point in the current UTC Monday-Sunday calendar week",
    window: "current UTC calendar week from Monday 00:00 through asOf",
    publicationStatus: "official",
    decisionGate: "NS-01 keeps WPCU official until Product DRI approval and PRD update",
    sourceFacts: ["chat_exchange_fact", "generation_fulfillment_fact", "subscription_lifecycle_fact"],
    sourceEvents: ["chat.exchange.completed.v2", "chat.exchange.corrected.v2", "generation.delivery.completed.v2", "subscription.activated.v2", "subscription.ended.v2"],
    version: 2,
    effectiveAt: "2026-07-12T00:00:00.000Z",
    validFrom: "2026-07-11T00:00:00.000Z",
    queryHash: "sha256:canonical-metric-engine-v2:north-star-wpcu-utc-calendar-week",
  },
  {
    ...canonicalMetricDefaults,
    key: "north_star.wscu",
    name: "Weekly Sustained Companion Users",
    description: "Distinct users with two QCEs for the same character across sessions and UTC days at least 12 hours apart.",
    businessQuestion: "How many users sustain a relationship across independent visits?",
    numerator: "distinct eligible sustained companion users",
    denominator: "not applicable (count metric)",
    window: "rolling 7 days ending at asOf",
    publicationStatus: "shadow",
    decisionGate: "NS-01",
    sourceFacts: ["chat_exchange_fact"],
    sourceEvents: ["chat.exchange.completed.v2", "chat.exchange.corrected.v2"],
    qualityState: "directional",
    decisionUse: "directional_only",
    queryHash: "sha256:canonical-metric-engine-v1:north-star-wscu-shadow",
  },
  {
    ...canonicalMetricDefaults,
    key: "diagnostic.wsr",
    name: "Weekly Sustained Relationships",
    description: "Distinct user-character pairs satisfying the WSCU sustained relationship rule.",
    businessQuestion: "How many distinct relationships sustain across independent visits?",
    numerator: "distinct sustained eligible user-character pairs",
    denominator: "not applicable (count metric)",
    grain: "user_character_pair",
    window: "rolling 7 days ending at asOf",
    sourceFacts: ["chat_exchange_fact"],
    sourceEvents: ["chat.exchange.completed.v2", "chat.exchange.corrected.v2"],
    qualityState: "directional",
    decisionUse: "directional_only",
    queryHash: "sha256:canonical-metric-engine-v1:diagnostic-wsr",
  },
  {
    ...canonicalMetricDefaults,
    key: "guardrail.wscru",
    name: "Weekly Sustained Creation Users",
    description: "Distinct users with successful deliveries from different requests on different UTC days at least 12 hours apart.",
    businessQuestion: "How many users sustain creation value across independent product days?",
    numerator: "distinct eligible sustained creation users",
    denominator: "not applicable (count metric)",
    sourceFacts: ["generation_fulfillment_fact"],
    sourceEvents: ["generation.delivery.completed.v2"],
    window: "rolling 7 days ending at asOf",
    publicationStatus: "shadow",
    decisionGate: "NS-01",
    qualityState: "directional",
    decisionUse: "directional_only",
    queryHash: "sha256:canonical-metric-engine-v1:guardrail-wscru-shadow",
  },
  {
    ...canonicalMetricDefaults,
    key: "business.wpscu",
    name: "Weekly Paying Sustained Companion Users",
    description: "WSCU users with an active paid subscription during a qualifying episode.",
    businessQuestion: "How much sustained companion value overlaps with paid status?",
    numerator: "distinct paying sustained companion users",
    denominator: "not applicable (count metric)",
    window: "rolling 7 days ending at asOf",
    publicationStatus: "shadow",
    decisionGate: "NS-01",
    sourceFacts: ["chat_exchange_fact", "subscription_lifecycle_fact"],
    sourceEvents: ["chat.exchange.completed.v2", "chat.exchange.corrected.v2", "subscription.activated.v2", "subscription.ended.v2"],
    qualityState: "directional",
    decisionUse: "directional_only",
    queryHash: "sha256:canonical-metric-engine-v1:business-wpscu-shadow",
  },
  {
    ...canonicalMetricDefaults,
    key: "activation.chat_24h",
    name: "Chat Activation 24h",
    description: "Eligible signup users completing their first QCE within 24 hours.",
    businessQuestion: "Do mature signup cohorts reach qualified conversation value in their first day?",
    numerator: "mature signup users with first QCE within 24h",
    denominator: "eligible signup users whose 24h observation window is mature",
    sourceFacts: ["customer_signup_fact", "chat_exchange_fact"],
    sourceEvents: ["customer.signup.completed.v2", "chat.exchange.completed.v2", "chat.exchange.corrected.v2"],
    window: "signup occurredAt through +24h",
    queryHash: "sha256:canonical-metric-engine-v1:activation-chat-24h",
  },
  {
    ...canonicalMetricDefaults,
    key: "activation.relationship_7d",
    name: "Relationship Activation 7d",
    description: "Eligible signup users satisfying the sustained same-character relationship rule within seven days.",
    businessQuestion: "Do mature signup cohorts establish a repeated relationship in their first week?",
    numerator: "mature signup users with a sustained same-character relationship within 7d",
    denominator: "eligible signup users whose 7d observation window is mature",
    sourceFacts: ["customer_signup_fact", "chat_exchange_fact"],
    sourceEvents: ["customer.signup.completed.v2", "chat.exchange.completed.v2", "chat.exchange.corrected.v2"],
    window: "signup occurredAt through +7d",
    queryHash: "sha256:canonical-metric-engine-v1:activation-relationship-7d",
  },
  {
    ...canonicalMetricDefaults,
    key: "activation.generation_7d",
    name: "Generation Activation 7d",
    description: "Eligible signup users receiving a valid displayable delivery within seven days.",
    businessQuestion: "Do mature signup cohorts receive successful creation value in their first week?",
    numerator: "mature signup users with a successful eligible delivery within 7d",
    denominator: "eligible signup users whose 7d observation window is mature",
    sourceFacts: ["customer_signup_fact", "generation_fulfillment_fact"],
    sourceEvents: ["customer.signup.completed.v2", "generation.delivery.completed.v2"],
    window: "signup occurredAt through +7d",
    queryHash: "sha256:canonical-metric-engine-v1:activation-generation-7d",
  },
  {
    ...canonicalMetricDefaults,
    key: "retention.same_character_d1",
    name: "Same-character D1",
    description: "First-QCE pairs returning to the same character on the exact next UTC product day.",
    businessQuestion: "Do qualified relationships return to the same character on D0+1?",
    numerator: "mature first-QCE pairs with a same-character QCE on exact D0+1",
    denominator: "first-QCE pair cohort mature through D0+1",
    grain: "user_character_pair",
    cohort: "first QCE user-character pair UTC product day",
    sourceFacts: ["chat_exchange_fact"],
    sourceEvents: ["chat.exchange.completed.v2", "chat.exchange.corrected.v2"],
    window: "exact D0+1 UTC product day",
    queryHash: "sha256:canonical-metric-engine-v1:retention-d1",
  },
  {
    ...canonicalMetricDefaults,
    key: "retention.same_character_d7",
    name: "Same-character D7",
    description: "First-QCE pairs returning to the same character on exact UTC D0+7.",
    businessQuestion: "Do qualified relationships return to the same character on D0+7?",
    numerator: "mature first-QCE pairs with a same-character QCE on exact D0+7",
    denominator: "first-QCE pair cohort mature through D0+7",
    grain: "user_character_pair",
    cohort: "first QCE user-character pair UTC product day",
    sourceFacts: ["chat_exchange_fact"],
    sourceEvents: ["chat.exchange.completed.v2", "chat.exchange.corrected.v2"],
    window: "exact D0+7 UTC product day",
    queryHash: "sha256:canonical-metric-engine-v1:retention-d7",
  },
  {
    ...canonicalMetricDefaults,
    key: "retention.same_character_w1",
    name: "Same-character W1 Return",
    description: "First-QCE pairs returning on any UTC product day from D0+7 through D0+13.",
    businessQuestion: "Do qualified relationships return during the following week?",
    numerator: "mature first-QCE pairs with a same-character QCE during D7-D13",
    denominator: "first-QCE pair cohort mature through D0+13",
    grain: "user_character_pair",
    cohort: "first QCE user-character pair UTC product day",
    sourceFacts: ["chat_exchange_fact"],
    sourceEvents: ["chat.exchange.completed.v2", "chat.exchange.corrected.v2"],
    window: "D0+7 through D0+13 UTC product days",
    queryHash: "sha256:canonical-metric-engine-v1:retention-w1",
  },
  {
    ...canonicalMetricDefaults,
    key: "conversion.paid_d7",
    name: "Paid Conversion D7",
    description: "Eligible signup cohort first entering active paid status within seven days.",
    businessQuestion: "What share of mature signup cohorts first become paid within seven days?",
    numerator: "mature signup users first active-paid within signup+7d",
    denominator: "eligible signup users whose 7d observation window is mature",
    sourceFacts: ["customer_signup_fact", "subscription_lifecycle_fact"],
    sourceEvents: ["customer.signup.completed.v2", "subscription.activated.v2", "subscription.ended.v2"],
    window: "signup occurredAt through +7d",
    queryHash: "sha256:canonical-metric-engine-v1:conversion-paid-d7",
  },
  {
    ...canonicalMetricDefaults,
    key: "conversion.paid_d30",
    name: "Paid Conversion D30",
    description: "Eligible signup cohort first entering active paid status within thirty days.",
    businessQuestion: "What share of mature signup cohorts first become paid within thirty days?",
    numerator: "mature signup users first active-paid within signup+30d",
    denominator: "eligible signup users whose 30d observation window is mature",
    sourceFacts: ["customer_signup_fact", "subscription_lifecycle_fact"],
    sourceEvents: ["customer.signup.completed.v2", "subscription.activated.v2", "subscription.ended.v2"],
    window: "signup occurredAt through +30d",
    queryHash: "sha256:canonical-metric-engine-v1:conversion-paid-d30",
  },
  {
    ...canonicalMetricDefaults,
    key: "relationship.qce_activation.v1",
    name: "Experiment QCE Activation 7d",
    description: "Mature actually exposed user subjects completing a QCE within seven days of first exposure.",
    businessQuestion: "Does an exposed experiment experience increase qualified conversation activation?",
    numerator: "mature exposed eligible user subjects with at least one QCE within 7d of first exposure",
    denominator: "unique eligible user subjects with an actual exposure and a fully mature 7d window",
    grain: "experiment_exposed_user",
    sourceFacts: ["experiment_exposure_fact", "chat_exchange_fact"],
    sourceEvents: ["experiment.exposed.v2", "chat.exchange.completed.v2", "chat.exchange.corrected.v2"],
    cohort: "first eligible experiment exposure per user and assignment version",
    window: "7 days after first actual exposure",
    maturity: "first exposure plus 7 complete days",
    dedupe: "first exposure per subject; distinct exchangeId within engagement session",
    attributionRule: "assignment-version exact exposure attribution",
    publicationStatus: "diagnostic",
    queryHash: "sha256:experiment-qce-activation-v1",
  },
  {
    ...canonicalMetricDefaults,
    key: "guardrail.support_contact_rate.v1",
    name: "Experiment Support Contact Rate 7d",
    description: "Mature actually exposed user subjects submitting a support request within seven days of first exposure.",
    businessQuestion: "Does an experiment increase customer support burden?",
    numerator: "mature exposed eligible user subjects with at least one canonical support request within 7d",
    denominator: "unique eligible user subjects with an actual exposure and a fully mature 7d window",
    grain: "experiment_exposed_user",
    sourceFacts: ["experiment_exposure_fact", "support_request_authority"],
    sourceEvents: ["experiment.exposed.v2", "support.request.submitted.v2"],
    cohort: "first eligible experiment exposure per user and assignment version",
    window: "7 days after first actual exposure",
    maturity: "first exposure plus 7 complete days",
    dedupe: "first support request outcome per exposed subject",
    attributionRule: "assignment-version exact exposure attribution",
    publicationStatus: "guardrail",
    queryHash: "sha256:experiment-support-contact-rate-v1",
  },
  {
    ...canonicalMetricDefaults,
    key: "cost.provider_variable_7d",
    name: "Provider Variable Cost 7d",
    description: "Canonical provider invocation cost recorded by AiUsageFact during the rolling seven-day window.",
    businessQuestion: "How much provider cost did eligible production AI invocations incur?",
    numerator: "sum of canonical AiUsageFact costMicros",
    denominator: "not applicable (cost total)",
    grain: "provider_invocation",
    sourceFacts: ["ai_usage_fact"],
    sourceEvents: ["ai.usage.recorded.v2"],
    cohort: "eligible production customer invocations with canonical provider cost",
    window: "rolling 7 days ending at asOf",
    maturity: "available after canonical invocation ingestion",
    dedupe: "sourceService + sourceEventId",
    attributionRule: "provider invocation authority; no cash-revenue inference",
    owner: "Finance Analytics",
    publicationStatus: "diagnostic",
    qualityState: "directional",
    decisionUse: "directional_only",
    queryHash: "sha256:ai-usage-provider-variable-cost-7d-v1",
    validationEvidence: ["AiUsageFact is canonical invocation-cost authority; pricing coverage remains visible."],
  },
  {
    ...canonicalMetricDefaults,
    key: "margin.character_contribution_7d",
    name: "Character Contribution Margin 7d",
    description: "Attributed cash revenue less variable provider cost, refunds, and credits for Character value paths.",
    businessQuestion: "Which Character releases create positive contribution margin?",
    numerator: "attributed net cash revenue minus provider cost, refunds, and credits",
    denominator: "not applicable (margin total)",
    grain: "character_release",
    sourceFacts: ["ai_usage_fact", "cash_attribution_fact"],
    sourceEvents: ["ai.usage.recorded.v2", "payment.cash_attribution.unavailable"],
    cohort: "eligible production value events with verified cash attribution",
    window: "rolling 7 days ending at asOf",
    maturity: "unavailable until payment cash attribution authority is connected",
    dedupe: "ledger/provider authority keys",
    attributionRule: "verified companion direct/assisted cash attribution only",
    owner: "Finance Analytics",
    publicationStatus: "diagnostic",
    qualityState: "invalid",
    decisionUse: "blocked",
    queryHash: "pending:character-contribution-margin-cash-authority-v1",
    validationEvidence: ["Cash attribution authority is unavailable; Dreamcoin consumption is not cash revenue."],
  },
]);
