-- Historical main-side character previews could be generated by the mock image
-- provider and then promoted into the real Character identity authority.
-- Preserve those rows for auditability, but remove every serving/identity link
-- so the owner must generate and select a real provider asset.
WITH synthetic_preview_assets AS (
  SELECT id
  FROM "media_assets"
  WHERE COALESCE("metadata"->>'source', '') = 'character_preview'
    AND COALESCE(("metadata"->>'synthetic')::boolean, FALSE) = TRUE
)
UPDATE "character_visual_profiles" profiles
SET "status" = 'archived'
WHERE profiles."status" = 'active'
  AND EXISTS (
    SELECT 1
    FROM synthetic_preview_assets assets
    WHERE profiles."anchorAssetIds" ? assets.id
  );

WITH synthetic_preview_assets AS (
  SELECT id
  FROM "media_assets"
  WHERE COALESCE("metadata"->>'source', '') = 'character_preview'
    AND COALESCE(("metadata"->>'synthetic')::boolean, FALSE) = TRUE
)
UPDATE "characters" characters
SET
  "imageAssetId" = NULL,
  "visibility" = 'private',
  "status" = 'draft'
FROM synthetic_preview_assets assets
WHERE characters."imageAssetId" = assets.id;

WITH synthetic_preview_jobs AS (
  SELECT jobs.id, jobs."draftId"
  FROM "character_preview_jobs" jobs
  JOIN "media_assets" assets ON assets.id = jobs."resultAssetId"
  WHERE COALESCE("assets"."metadata"->>'source', '') = 'character_preview'
    AND COALESCE(("assets"."metadata"->>'synthetic')::boolean, FALSE) = TRUE
)
UPDATE "character_drafts" drafts
SET "previewJobId" = NULL
FROM synthetic_preview_jobs jobs
WHERE drafts.id = jobs."draftId"
  AND drafts."previewJobId" = jobs.id;

UPDATE "media_assets"
SET
  "characterId" = NULL,
  "visibility" = 'unlisted',
  "metadata" = "metadata" || jsonb_build_object(
    'quarantined', TRUE,
    'quarantineReason', 'synthetic_character_preview'
  )
WHERE COALESCE("metadata"->>'source', '') = 'character_preview'
  AND COALESCE(("metadata"->>'synthetic')::boolean, FALSE) = TRUE;
